---
title: "1_link_metadata.Rmd"
author: "Andrea Estandia"
date: "11/01/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
source("./src/0.0_wytham_great_tit_source.R")
```

Read both list of individuals from the 10K and 600K datasets 
```{r}
ind_10K <- read.csv(file.path(data_path,
                             "plink",
                             "common_snps",
                             "tmp_files",
                             "10K_list_ind.csv"),
                    header=F) %>% 
  rename(sample_name=V1) %>% 
  separate(sample_name, c("sample_name", "rubbish")) %>% 
  dplyr::select(-rubbish)

ind_600K <- read.csv(file.path(data_path,
                             "plink",
                             "common_snps",
                             "tmp_files",
                             "600K_list_ind.csv"),
                    header=F) %>% 
  rename(sample_name=V1) 

common_dataset <- read.table(file.path(data_path,
                             "plink",
                             "common_snps",
                             "common_snps_merged_dataset.fam"),
                    header=F) %>% 
  select(V2) %>% 
  rename(sample_name=V2) 
  
```

Detect immigrants vs residents
```{r}
process_data <- function(ind_data) {
  total_data <- read.csv(file.path(data_path,
                                    "wytham_ringing_breeding",
                                    "ebmp_database_ringing_record_export_GT&BT_all.csv")) %>% 
    filter(bto_species_code == "GRETI") %>% 
    filter(bto_ring %in% ind_data$sample_name) %>% 
    distinct(bto_ring, .keep_all = TRUE)

  n_total_data <- dim(total_data)[1]

  resident_data <- read.csv(file.path(data_path,
                                       "wytham_ringing_breeding",
                                       "ebmp_database_ringing_record_export_GT&BT_all.csv")) %>% 
    filter(bto_species_code == "GRETI") %>% 
    filter(age == 1) %>% # All age=1 are born in the population so residents
    filter(bto_ring %in% ind_data$sample_name) %>% 
    distinct(bto_ring, .keep_all = TRUE)

  n_resident_data <- dim(resident_data)[1]

  immigrants_data <- read.csv(file.path(data_path,
                                          "wytham_ringing_breeding",
                                          "ebmp_database_ringing_record_export_GT&BT_all.csv")) %>% 
    filter(bto_species_code == "GRETI") %>% 
    filter(bto_ring %in% ind_data$sample_name) %>% 
    filter(bto_ring %!in% resident_data$bto_ring) %>% 
    distinct(bto_ring, .keep_all = TRUE)

  n_immigrants_data <- dim(immigrants_data)[1]

  return(list(
    total_data = total_data,
    n_total_data = n_total_data,
    resident_data = resident_data,
    n_resident_data = n_resident_data,
    immigrants_data = immigrants_data,
    n_immigrants_data = n_immigrants_data
  ))
}

# Usage for ind_600K
result_600K <- process_data(ind_600K)
(result_600K$n_resident_data)
#617
(result_600K$n_immigrants_data)
#298

# Usage for ind_10K
result_10K <- process_data(ind_10K)
(result_10K$n_resident_data)
#1420
(result_10K$n_immigrants_data)
#1022

result_10K

result_common <- process_data(common_dataset)

ind_w_bto_info <- result_common$total_data$bto_ring
```

Repeated individuals 
```{r}
common_ind <- 
  ind_10K %>% 
  filter(sample_name %in% ind_600K$sample_name)
```

Add phenotype (immigrant or resident to fam file)
```{r}
wytham_fam <- read.table(file.path(data_path,
                                       "plink",
                                   "10K",
                                   "Wytham10K.fam"), header = FALSE) %>% 
  rename(bto_ring=V2)

imm_res <- read.csv(file.path(data_path,
                                       "plink",
                                   "10K",
                                   "10K_imm_res.csv"), header = T)

# Merge the data frames based on the V2 column
merged_data <- wytham_fam %>% 
  left_join(imm_res, by = "bto_ring") %>% 
  select(V1, bto_ring, V3, V4, V5, imm_res)

write.table(merged_data, file.path(data_path,
                                       "plink",
                                   "10K",
                                   "Wytham10K_new.fam"),
            row.names = F,
            col.names = F,
            quote = F)

```

